server:
<<<<<<< HEAD
  port: 8082
spring:
  application:
    name: HOTEL-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: configserver:http://localhost:8085
    profiles:
      active: dev
=======
  port: 8081
spring:
  application:
    name: USER-SERVICE

#  datasource:
#    url: jdbc:mysql://localhost:3306/microservices
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: dev
>>>>>>> f2a96bc5ac54d492a89acc434181ee0b1ef89923
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
<<<<<<< HEAD
#      defaultZone: http://localhost:8761/eureka
=======
#      defaultZone: http://localhost:8761/eureka
>>>>>>> f2a96bc5ac54d492a89acc434181ee0b1ef89923
